
// Autogenerated file. Do not edit!!!

#ifndef HARDCODE_XML_VALUES
NUM_CONCEPT_TYPES = (ConceptTypes)GC.getNumConceptInfos();
NUM_FATHERCATEGORY_TYPES = (FatherCategoryTypes)GC.getNumFatherCategoryInfos();
NUM_UNITCOMBAT_TYPES = (UnitCombatTypes)GC.getNumUnitCombatInfos();
NUM_BUILDINGCLASS_TYPES = (BuildingClassTypes)GC.getNumBuildingClassInfos();
NUM_BUILDING_TYPES = (BuildingTypes)GC.getNumBuildingInfos();
NUM_SPECIALBUILDING_TYPES = (SpecialBuildingTypes)GC.getNumSpecialBuildingInfos();
NUM_CIV_EFFECT_TYPES = (CivEffectTypes)m_paCivEffectInfo.size();
NUM_ALARM_TYPES = (AlarmTypes)GC.getNumAlarmInfos();
NUM_CIVILIZATION_TYPES = (CivilizationTypes)GC.getNumCivilizationInfos();
NUM_LEADER_TYPES = (LeaderHeadTypes)GC.getNumLeaderHeadInfos();
NUM_TRAIT_TYPES = (TraitTypes)GC.getNumTraitInfos();
NUM_UNIT_ARTSTYLE_TYPES = (UnitArtStyleTypes)GC.getNumUnitArtStyleTypeInfos();
NUM_ACHIEVE_TYPES = (AchieveTypes)GC.getNumAchieveInfos();
NUM_EVENT_TYPES = (EventTypes)GC.getNumEventInfos();
NUM_EVENTTRIGGER_TYPES = (EventTriggerTypes)GC.getNumEventTriggerInfos();
NUM_CIVIC_TYPES = (CivicTypes)GC.getNumCivicInfos();
NUM_CIVICOPTION_TYPES = (CivicOptionTypes)GC.getNumCivicOptionInfos();
NUM_CLIMATE_TYPES = (ClimateTypes)GC.getNumClimateInfos();
NUM_CULTURELEVEL_TYPES = (CultureLevelTypes)GC.getNumCultureLevelInfos();
NUM_DIPLOMACY_TYPES = (DiplomacyTypes)GC.getNumDiplomacyInfos();
NUM_EMPHASIZE_TYPES = (EmphasizeTypes)GC.getNumEmphasizeInfos();
NUM_ERA_TYPES = (EraTypes)GC.getNumEraInfos();
NUM_EUROPE_TYPES = (EuropeTypes)GC.getNumEuropeInfos();
NUM_FATHER_TYPES = (FatherTypes)GC.getNumFatherInfos();
NUM_FATHER_POINT_TYPES = (FatherPointTypes)GC.getNumFatherPointInfos();
NUM_GAMESPEED_TYPES = (GameSpeedTypes)GC.getNumGameSpeedInfos();
NUM_GOODY_TYPES = (GoodyTypes)GC.getNumGoodyInfos();
NUM_HANDICAP_TYPES = (HandicapTypes)GC.getNumHandicapInfos();
NUM_HURRY_TYPES = (HurryTypes)GC.getNumHurryInfos();
NUM_SEALEVEL_TYPES = (SeaLevelTypes)GC.getNumSeaLevelInfos();
NUM_VICTORY_TYPES = (VictoryTypes)GC.getNumVictoryInfos();
NUM_EFFECT_TYPES = (EffectTypes)GC.getNumEffectInfos();
NUM_ROUTE_TYPES = (RouteTypes)GC.getNumRouteInfos();
NUM_BONUS_TYPES = (BonusTypes)GC.getNumBonusInfos();
NUM_FEATURE_TYPES = (FeatureTypes)GC.getNumFeatureInfos();
NUM_IMPROVEMENT_TYPES = (ImprovementTypes)GC.getNumImprovementInfos();
NUM_BUILD_TYPES = (BuildTypes)GC.getNumBuildInfos();
NUM_PROFESSION_TYPES = (ProfessionTypes)GC.getNumProfessionInfos();
NUM_PROMOTION_TYPES = (PromotionTypes)GC.getNumPromotionInfos();
NUM_SPECIALUNIT_TYPES = (SpecialUnitTypes)GC.getNumSpecialUnitInfos();
NUM_UNITCLASS_TYPES = (UnitClassTypes)GC.getNumUnitClassInfos();
NUM_UNIT_TYPES = (UnitTypes)GC.getNumUnitInfos();
#endif
